
corpus_location:
    - /Volumes/langdoc/langs/kpv

session_name_prefixes:
    - kpv_csys
    - kpv_izva
    - kpv_let
    - kpv_lit
    - kpv_luz
    - kpv_skar
    - kpv_udo
    - kpv_usys
    - kpv_uvyc
    - kpv_vym

session_name_middle:
    - \d{8}

required_tier_types:
    - refT
    - orthT
    - ft-engT
    - ft-rusT

parent_child_patterns:
    - ref, orth
    - ref, ft-eng
    - ref, ft-rus
    - orth, word
    - word, lemma
    - lemma, pos
    - pos, morph
    
manually_verified_files:
    - kpv_usys20120701_IVK-M-1930
    - kpv_izva19591100-05582_1az
    - kpv_izva19660000Kolva-1-4
    - kpv_izva19591100-05582_3az
    - kpv_izva19570000-290_3bz-Bakur
    - kpv_izva19850730-1Igusev_doryn
    - kpv_izva20090222SaamiKomi-1
    - kpv_izva20090222SaamiKomi-2
    - kpv_izva20140404IgusevJA
    - kpv_izva20000320-1AndrejevaMM
    - kpv_izva19591216-05582_2az
    - kpv_izva19570000-291_1a-Brikalansk
    - kpv_izva19570000-292_1a-Kolva-story
    - kpv_izva19570000-291_1a-Selajur