
corpus_location:
    - /Volumes/langdoc/langs/kpv

session_name_prefixes:
    - kpv_csys
    - kpv_izva
    - kpv_let
    - kpv_lit
    - kpv_luz
    - kpv_skar
    - kpv_udo
    - kpv_usys
    - kpv_uvyc
    - kpv_vym

session_name_middle:
    - \d{8}

required_tier_types:
    - refT
    - orthT
    - ft-engT
    - ft-rusT

parent_child_patterns:
    - ref, orth
    - ref, ft-eng
    - ref, ft-rus
    - orth, word
    - word, lemma
    - lemma, pos
    - pos, morph
  
manually_verified_files:
    - kpv_izva20191205-example
    - kpv_izva19570000-290_3bz-Bakur
